const char INDEX_HTML[] =
"<!DOCTYPE HTML>"
"<html>"
"<head>"
"<meta content=\"text/html; charset=ISO-8859-1\""
" http-equiv=\"content-type\">"
"<meta name = \"viewport\" content = \"width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable=0\">"
"<title>ALBOT ECMO WIFI SETUP</title>"
"<style>"
"\"body { background-color: #808080; font-family: Arial, Helvetica, Sans-Serif; Color: #000000; text-align:center;}\""
"</style>"
"</head>"
"<body>"
"<pre><h3>                  ALBOT ECMO                     </h3></pre>"
"<h4>Enter the WiFi Credentials</h4>"
"<form action=\"/\" method=\"post\">"
"<p>"
"<label>SSID:&nbsp;</label>"
"<input maxlength=\"30\" name=\"ssid\"><br>"
"<label>KEY:&nbsp;&nbsp;</label><input maxlength=\"30\" name=\"password\"><br>"
"<br>"
"<input type=\"submit\" value=\"CONNECT\">"
"</p>"
"</form>"
"<marquee>&copy;AlbotTechnologies</marquee>"
"</body>"
"</html>";
